"""
Anomaly Alert Handler

Handles anomaly detection alerts and notifications.
Can be called directly from the anomaly detection service.
"""
import requests
from datetime import datetime
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.config import get_settings
from core.database import engine
from sqlalchemy import text
from loguru import logger

settings = get_settings()


class AnomalyAlertHandler:
    """Handles anomaly alerts and notifications"""
    
    def __init__(self):
        self.telegram_enabled = False
        self.email_enabled = False
        
    def log_anomaly(self, anomaly_data):
        """Log anomaly to database"""
        try:
            with engine.connect() as conn:
                conn.execute(text("""
                    INSERT INTO anomalies 
                    (stock_id, detected_at, anomaly_type, severity, anomaly_score, description)
                    VALUES (:stock_id, :detected_at, :anomaly_type, :severity, :score, :description)
                """), {
                    'stock_id': anomaly_data['stock_id'],
                    'detected_at': anomaly_data.get('timestamp', datetime.now()),
                    'anomaly_type': anomaly_data['anomaly_type'],
                    'severity': anomaly_data['severity'],
                    'score': anomaly_data['score'],
                    'description': anomaly_data['description']
                })
                conn.commit()
                logger.info(f"✅ Logged anomaly: {anomaly_data['anomaly_type']} for {anomaly_data['ticker']}")
                
        except Exception as e:
            logger.error(f"Error logging anomaly: {e}")
    
    def send_telegram_alert(self, anomaly_data):
        """Send Telegram alert based on severity"""
        if not self.telegram_enabled:
            logger.info(f"📱 Telegram disabled. Would send: {anomaly_data['severity']} alert")
            return
        
        try:
            # Different message templates based on anomaly type
            if anomaly_data['anomaly_type'] == 'VOLUME_SPIKE':
                message = f"""
⚠️ Volume Spike Detected!

Stock: {anomaly_data['ticker']}
Type: {anomaly_data['anomaly_type']}
Severity: {anomaly_data['severity']}
Score: {anomaly_data['score']}

Description: {anomaly_data['description']}
                """
                
            elif anomaly_data['anomaly_type'] == 'PRICE_MANIPULATION':
                message = f"""
🚨 CRITICAL: Market Manipulation Suspected!

Stock: {anomaly_data['ticker']}
Type: {anomaly_data['anomaly_type']}
Severity: {anomaly_data['severity']}
Score: {anomaly_data['score']}

Description: {anomaly_data['description']}

REQUIRES IMMEDIATE INVESTIGATION!
                """
                
            else:
                message = f"""
⚠️ Anomaly Detected

Stock: {anomaly_data['ticker']}
Type: {anomaly_data['anomaly_type']}
Severity: {anomaly_data['severity']}
Score: {anomaly_data['score']}

{anomaly_data['description']}
                """
            
            logger.info(f"Telegram alert sent: {message[:50]}...")
            
            # TODO: Implement actual Telegram API call
            # import telegram
            # bot = telegram.Bot(token=settings.telegram_bot_token)
            # bot.send_message(chat_id=settings.telegram_chat_id, text=message)
            
        except Exception as e:
            logger.error(f"Error sending Telegram alert: {e}")
    
    def send_email_to_cmf(self, anomaly_data):
        """Send email to CMF for critical anomalies"""
        if not self.email_enabled:
            logger.info(f"📧 Email disabled. Would notify CMF about: {anomaly_data['ticker']}")
            return
        
        try:
            subject = f"Market Anomaly Report - {anomaly_data['ticker']}"
            body = f"""
Conseil du Marché Financier,

An anomaly has been detected that requires regulatory attention:

Stock Information:
- Ticker: {anomaly_data['ticker']}
- Stock ID: {anomaly_data['stock_id']}

Anomaly Details:
- Type: {anomaly_data['anomaly_type']}
- Severity: {anomaly_data['severity']}
- Detection Score: {anomaly_data['score']}
- Timestamp: {anomaly_data.get('timestamp', datetime.now())}

Description:
{anomaly_data['description']}

This automated alert was generated by the Carthage Alpha market surveillance system.

---
Carthage Alpha - Intelligent Trading Assistant
            """
            
            logger.info(f"Email to CMF prepared: {subject}")
            
            # TODO: Implement actual email sending
            # import smtplib
            # from email.mime.text import MIMEText
            # msg = MIMEText(body)
            # msg['Subject'] = subject
            # msg['From'] = settings.email_from
            # msg['To'] = 'regulator@cmf.tn'
            # smtp.send_message(msg)
            
        except Exception as e:
            logger.error(f"Error sending email to CMF: {e}")
    
    def handle_anomaly(self, anomaly_data):
        """
        Main handler for anomaly alerts
        
        Args:
            anomaly_data: dict with keys:
                - stock_id: int
                - ticker: str
                - anomaly_type: str (VOLUME_SPIKE, PRICE_MANIPULATION, etc.)
                - severity: str (LOW, MEDIUM, HIGH, CRITICAL)
                - score: float
                - description: str
                - timestamp: datetime (optional)
        """
        logger.info("=" * 60)
        logger.info(f"🚨 Handling Anomaly: {anomaly_data['anomaly_type']}")
        logger.info("=" * 60)
        
        # 1. Log to database (always)
        self.log_anomaly(anomaly_data)
        
        # 2. Send alerts based on severity
        severity = anomaly_data['severity']
        
        if severity in ['LOW']:
            # Just log, no alerts
            logger.info("ℹ️  Low severity - logged only")
            
        elif severity in ['MEDIUM']:
            # Telegram only
            self.send_telegram_alert(anomaly_data)
            
        elif severity in ['HIGH']:
            # Telegram + log
            self.send_telegram_alert(anomaly_data)
            logger.warning(f"⚠️  High severity anomaly: {anomaly_data['ticker']}")
            
        elif severity in ['CRITICAL']:
            # Telegram + Email CMF
            self.send_telegram_alert(anomaly_data)
            self.send_email_to_cmf(anomaly_data)
            logger.critical(f"🚨 CRITICAL anomaly: {anomaly_data['ticker']}")
        
        logger.info("✅ Anomaly handled successfully")
        logger.info("=" * 60)


# Example usage
if __name__ == "__main__":
    handler = AnomalyAlertHandler()
    
    # Test with sample data
    test_anomaly = {
        'stock_id': 1,
        'ticker': 'SFBT',
        'anomaly_type': 'VOLUME_SPIKE',
        'severity': 'HIGH',
        'score': 3.5,
        'description': 'Volume 350% above 30-day average',
        'timestamp': datetime.now()
    }
    
    handler.handle_anomaly(test_anomaly)
